app_name = "fbr_v12"
app_title = "Retired Digital Invoicing history"
app_publisher = "Ledgix"
app_description = "Read-only historical app identity; new installation prohibited"
app_email = "alishahwaiz96@gmail.com"
app_license = "mit"
before_install = "fbr_v12.retired.reject"
doc_events = {}
scheduler_events = {}
