#!/usr/bin/env bash
set -Eeuo pipefail

METADATA=""
EXPECTED_SITE=""

info() { printf '[INFO] %s\n' "$*"; }
ok() { printf '[OK] %s\n' "$*"; }
die() { printf '[ERROR] %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<'EOF'
Usage: deploy/verify_backup_set.sh --metadata FILE [--site SITE]

Revalidates a Ledgix backup metadata file and the checksum-protected database,
public files, private files and site configuration artifacts it references.
This command is read-only.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --metadata) [[ $# -ge 2 ]] || die '--metadata requires a value'; METADATA="$2"; shift 2 ;;
    --site) [[ $# -ge 2 ]] || die '--site requires a value'; EXPECTED_SITE="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

[[ -n "$METADATA" ]] || die '--metadata is required'
[[ -f "$METADATA" ]] || die "metadata file not found: $METADATA"
command -v sha256sum >/dev/null 2>&1 || die 'sha256sum is required'
command -v stat >/dev/null 2>&1 || die 'stat is required'
command -v realpath >/dev/null 2>&1 || die 'realpath is required'

MODE_TEXT="$(stat -c '%a' "$METADATA")"
MODE=$((8#$MODE_TEXT))
(( (MODE & 077) == 0 )) || die "metadata must not be group/world accessible: mode $MODE_TEXT"
[[ "$(stat -c '%u' "$METADATA")" == "$(id -u)" ]] || die 'metadata must be owned by the current user'

# The metadata file is generated by backup_safe.sh, stored under the site's
# private backup directory and must be owner-only before it is sourced.
# shellcheck disable=SC1090
source "$METADATA"

for variable in site backup_dir database_file public_files_file private_files_file site_config_file sha256_manifest; do
  [[ -n "${!variable:-}" ]] || die "metadata is missing required field: $variable"
done
for flag in verified_database verified_public_files verified_private_files verified_site_config verified_checksums; do
  [[ "${!flag:-0}" == "1" ]] || die "metadata verification flag is not green: $flag"
done

if [[ -n "$EXPECTED_SITE" && "$site" != "$EXPECTED_SITE" ]]; then
  die "backup site mismatch: expected $EXPECTED_SITE, metadata belongs to $site"
fi

BACKUP_ROOT="$(realpath -m "$backup_dir")"
for artifact in "$database_file" "$public_files_file" "$private_files_file" "$site_config_file" "$sha256_manifest"; do
  [[ -s "$artifact" ]] || die "backup artifact is missing or empty: $artifact"
  ARTIFACT_REAL="$(realpath -m "$artifact")"
  case "$ARTIFACT_REAL" in
    "$BACKUP_ROOT"/*) ;;
    *) die "backup artifact escapes recorded backup directory: $artifact" ;;
  esac
done

CONFIG_MODE_TEXT="$(stat -c '%a' "$site_config_file")"
CONFIG_MODE=$((8#$CONFIG_MODE_TEXT))
(( (CONFIG_MODE & 077) == 0 )) || die "site config backup must be owner-only: mode $CONFIG_MODE_TEXT"

printf '\n===== VERIFY BACKUP SET =====\n'
info "site: $site"
info "metadata: $METADATA"
info "backup directory: $BACKUP_ROOT"
(
  cd "$BACKUP_ROOT"
  sha256sum -c "$(basename "$sha256_manifest")"
)

ok "backup set is checksum-valid and complete for $site"
printf 'backup_set_verified=true\n'
